spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/voll_med_api
spring.datasource.username=${BANCO_USERNAME}
spring.datasource.password=${BANCO_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081